### ISSUE TITLE
Remove testing on Appveyor

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppetlabs-exec#82]
Appveyor testing is enabled however there are no actual spec unit tests, and the rubucop linting etc. is doubling up from Travis. So there appears to be no value in testing on Appveyor.

At the very least, the spec testing should be removed as it's wasting time and Appveyor resources.

**Comment by pmcmaw** [comment]
Hey @glennsarti we now use litmus to run acceptance tests on the machines therefore I am going to close this issue. I hope you are happy with this resolution. If you disagree please feel free to reopen or reply. 

Also on a side note, I hope your keeping well :-)
